### PR TITLE
Bookstore: styling

### PR DESCRIPTION
**Pull request by Ntwali-Josue**
### In this Pull Request, I:

- [x] Add styles to the page.

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @Ntwali-Josue 

Good job working on the project so far! 
✔️  Your linters are passing
✔️ You followed the zeplin design
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x] Please add the icon at the end of the navbar as given in the zeplin design
### Zeplin design
Screenshot 2021-12-10 at 19 04 47

### Your design
Screenshot 2021-12-10 at 19 02 43

- [ ] The Bookstore CMS title should be aligned with the start of your first card, please align it properly.
- [ ] Kindly make current chapter, update progress and Add new book all uppercase letters.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- I would suggest you make the screenshot on your README a screenshot of how your project looks at the moment and not the one provided by Microverse.
- Also consider adding author to your README, it should contain your name, your GitHub, LinkedIn and Twitter handle. You can check out the structure [here](https://github.com/microverseinc/readme-template)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Ntwali-Josue** [comment]
Hey @Ghiftee, thanks for the reviews 🤝 , I have worked on them.

**Review by dasileker — APPROVED** [review]
## **Hi @Ntwali-Josue,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ntwali-Josue** [comment]
Thanks @dasileker for your appproval 🥳

**Pull request merged**
